// <auto-generated />
using System;
using BlogProjetoFinal.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogProjetoFinal.Api.Migrations
{
    [DbContext(typeof(BlogProjetoFinalDbContext))]
    [Migration("20220921234122_UpdatesEnities")]
    partial class UpdatesEnities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlogProjetoFinal.Api.Domain.Entities.Artigo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("varchar(5000)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tb_artigo", (string)null);
                });

            modelBuilder.Entity("BlogProjetoFinal.Api.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("tb_categoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAtualizacao = new DateTime(2022, 9, 21, 20, 41, 21, 906, DateTimeKind.Local).AddTicks(7594),
                            DataCriacao = new DateTime(2022, 9, 21, 20, 41, 21, 906, DateTimeKind.Local).AddTicks(7585),
                            NomeCategoria = "Backend"
                        },
                        new
                        {
                            Id = 2,
                            DataAtualizacao = new DateTime(2022, 9, 21, 20, 41, 21, 906, DateTimeKind.Local).AddTicks(7597),
                            DataCriacao = new DateTime(2022, 9, 21, 20, 41, 21, 906, DateTimeKind.Local).AddTicks(7596),
                            NomeCategoria = "Frontend"
                        },
                        new
                        {
                            Id = 3,
                            DataAtualizacao = new DateTime(2022, 9, 21, 20, 41, 21, 906, DateTimeKind.Local).AddTicks(7598),
                            DataCriacao = new DateTime(2022, 9, 21, 20, 41, 21, 906, DateTimeKind.Local).AddTicks(7597),
                            NomeCategoria = "Mobile"
                        },
                        new
                        {
                            Id = 4,
                            DataAtualizacao = new DateTime(2022, 9, 21, 20, 41, 21, 906, DateTimeKind.Local).AddTicks(7599),
                            DataCriacao = new DateTime(2022, 9, 21, 20, 41, 21, 906, DateTimeKind.Local).AddTicks(7599),
                            NomeCategoria = "Cloud"
                        },
                        new
                        {
                            Id = 5,
                            DataAtualizacao = new DateTime(2022, 9, 21, 20, 41, 21, 906, DateTimeKind.Local).AddTicks(7600),
                            DataCriacao = new DateTime(2022, 9, 21, 20, 41, 21, 906, DateTimeKind.Local).AddTicks(7600),
                            NomeCategoria = "Testes"
                        },
                        new
                        {
                            Id = 6,
                            DataAtualizacao = new DateTime(2022, 9, 21, 20, 41, 21, 906, DateTimeKind.Local).AddTicks(7601),
                            DataCriacao = new DateTime(2022, 9, 21, 20, 41, 21, 906, DateTimeKind.Local).AddTicks(7601),
                            NomeCategoria = "Arquitetura"
                        });
                });

            modelBuilder.Entity("BlogProjetoFinal.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeDeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tb_usuario", (string)null);
                });

            modelBuilder.Entity("BlogProjetoFinal.Api.Domain.Entities.Artigo", b =>
                {
                    b.HasOne("BlogProjetoFinal.Api.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Artigos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogProjetoFinal.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Artigos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BlogProjetoFinal.Api.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Artigos");
                });

            modelBuilder.Entity("BlogProjetoFinal.Api.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Artigos");
                });
#pragma warning restore 612, 618
        }
    }
}
